apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/halkyonio/rhtap-buildpack-demo-3?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    appstudio.openshift.io/request: configure-pac
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-event: '[push]'
    pipelinesascode.tekton.dev/on-target-branch: '[main]'
    pipelinesascode.tekton.dev/pipeline: https://raw.githubusercontent.com/redhat-buildpacks/catalog/main/tekton/pipeline/rhtap/01/pipeline-buildpacks.yaml
  labels:
    appstudio.openshift.io/application: rhtap-buildpack-demo-3
    appstudio.openshift.io/component: rhtap-buildpack-demo-3
    pipelines.appstudio.openshift.io/type: build
    rhtap.snowdrop.dev/build: "test-4"
  name: rhtap-buildpack-demo-3
  namespace: cmoullia-tenant
spec:
  params:
    - name: git-url
      value: '{{repo_url}}'
    - name: image-expires-after
      value: 5d
    - name: output-image
      value: quay.io/redhat-user-workloads/cmoullia-tenant/rhtap-buildpack-demo-3/rhtap-buildpack-demo-3:build-{{revision}}
    - name: path-context
      value: .
    - name: revision
      value: '{{revision}}'
    - name: sourceSubPath
      value: .
    - name: cnbLogLevel
      value: debug
    - name: cnbBuilderImage
      value: paketocommunity/builder-ubi-base
    - name: cnbBuildImage
      value: paketocommunity/build-ubi-base
    - name: cnbRunImage
      value: paketocommunity/run-ubi-base
    - name: cnbBuildEnvVars
      value: []
  pipelineRef:
    name: pipeline-rhtap
  workspaces:
    - name: workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
        status: {}
    - name: git-auth
      secret:
        secretName: '{{ git_auth_secret }}'
